### PR TITLE
update module version to 1.0.7

### PR DESCRIPTION
**Pull request by omgitsdev**
@aleksa-andersinnovation Will this have any adverse effects with regard to packagist/composer/etc.?

### CODE REVIEW

**Comment by aleksa-andersinnovation** [comment]
No, but module.xml is not intended to specify module version but database schema version, version should be specified in composer.json

**Comment by omgitsdev** [comment]
@aleksa-andersinnovation Currently it seems like the version number that we exposed to the source in BF-109 is coming from this  file. I was hoping to expose the current package version. Is there another approach we should take, then?

**Comment by aleksa-andersinnovation** [comment]
Best place to store and pull from is composer.json file in module root, but I see that's been removed, were there any problems with that? If not then we can use that, or as alternative we can store it in a constant of bread payment model.

**Comment by omgitsdev** [comment]
Oh, okay great - if we're able to pull the version number out of the composer file and be displayed in the code, let's do that. Can you please make that change?

**Pull request closed without merging**
